#!/bin/bash

set -euo pipefail

export NEON_SDK_PATH=/opt/neon-sdk/$(uname -m)
export PATH=${NEON_SDK_PATH}/gcc-${GCC_VERSION}/bin:$PATH
export LD_LIBRARY_PATH=${NEON_SDK_PATH}/gcc-${GCC_VERSION}/lib64:$LD_LIBRARY_PATH
export NINJA_RELEASE_URL=https://github.com/Kitware/ninja/releases/download
export NINJA_VERSION=1.11.1.g95dee.kitware.jobserver-1
export GCC_VERSION=13.3.0
export LLVM_VERSION=llvmorg-20.1.4
export CMAKE_VERSION=3.28.3
export VULKAN_SDK_VERSION=1.4.313.0

scripts/install-ninja
scripts/build-cmake
scripts/build-gcc
scripts/build-llvm
scripts/build-vulkan-sdk
